-- 初始化数据库时执行的用户初始化逻辑
CREATE USER 'shiki'@'%' IDENTIFIED BY '666666';
GRANT ALL PRIVILEGES ON *.* TO 'shiki'@'%' WITH GRANT OPTION;

CREATE USER 'nacos'@'%' IDENTIFIED BY 'nacos';
GRANT ALL PRIVILEGES ON *.* TO 'nacos'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;