spring:
  application:
    name: sso-client
server:
  port: 9000

# sa-token配置
sa-token:
  # SSO-相关配置
  sso-client:
    # SSO-Server 端主机地址
    server-url: http://sa-sso-server.com:9001
  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引 (默认为0)
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s