profile:
  server:
    port: 8001

  mysql:
    host: 172.18.181.2
    name: root
    password: 123456
    database: vsblog

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  # 文章搜索策略
  search:
    mode: elasticsearch
    elasticsearch:
      host: localhost
      port: 9200
      scheme: http

  upload:
    mode: minio
    minio:
      url: http://localhost:9001/
      endpoint: http://localhost:9000
      accessKey: shiki
      secretKey: zcx123456
      bucketName: vsblog

    # 最大上传文件大小
    maxFileSize: 10MB
    maxRequestSize: 100MB

#  redisson:
#    address: 127.0.0.1
#    port: 6379
#    password: 123456