version: "3"

services:
  # redis容器
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
    networks:
      - vsnet
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # mysql容器
  mysql:
    image: mysql:8.0
    container_name: my-sql
    ports:
      - "3306:3306"
    env_file:
    # root配置与时区
      - ./mysql/env/mysql.env
    volumes:
      - ./mysql/conf:/etc/mysql/conf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - vsnet


networks:
  vsnet:
    driver: bridge