server:
  port: 8000

spring:
  application:
    name: vsblog-gateway

  # 仅使用网关而不使用mvc
  main:
    web-application-type: reactive

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: localhost:8848

    gateway:
      routes:
        - id: vsblog-auth
          uri: lb://vsblog-auth
          predicates:
            - Path=/auth/**

        - id: vsblog-user
          uri: lb://vsblog-user
          predicates:
            - Path=/user/**

        - id: vsblog-article
          uri: lb://vsblog-article
          predicates:
            - Path=/articles/**, /adminArticles/**

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      lettuce:
        # 配置redis连接池，分别为最大用户连接数，最大空闲连接数，最小空闲连接数，最大连接等待时间
        pool:
          max-active: 10
          max-wait: 100ms
          max-idle: 5
          min-idle: 0

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: true
  cookie:
    domain: velvetshiki.com

# knife4j网关文档聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    routes:
      - name: auth
        service-name: vsblog-auth
        url: /auth/v3/api-docs
        # 路由前缀
        context-path: /
        # 排序
        order: 1

      - name: user
        service-name: vsblog-user
        url: /user/v3/api-docs
        context-path: /
        order: 2

      - name: articles
        service-name: vsblog-article
        url: /articles/v3/api-docs
        context-path: /
        order: 3
