spring:
  application:
    name: _2024_10_18
  # spring security默认基于内存的用户配置
#  security:
#    user:
#      name: shiki
#      password: 123

# Knife4j开启
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志打印
logging:
  # 每个包的日志输出级别
  level:
    root: info
    com.vs: DEBUG
    org.springframework.security: DEBUG

  # 文件输出
#  file:
    # windows 绝对路径
#    path: D:\Code\Github\Java-Repo\demo\_2024_10_18
    # windows 相对路径
#    path: log/

    # linux路径
    # path: /var/log/myapp
#    name: log/demo.log
  #    name: D:\Code\Github\Java-Repo\demo\_2024_10_18\demo.log

  # 指定日志输出格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"