spring:
  application:
    name: _2024_10_18
  # spring security默认基于内存的用户配置
#  security:
#    user:
#      name: shiki
#      password: 123

#  redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      lettuce:
        # 配置redis连接池，分别为最大用户连接数，最大空闲连接数，最小空闲连接数，最大连接等待时间
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 0
          max-wait: 100ms

# Knife4j开启
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志打印
logging:
  # 每个包的日志输出级别
  level:
    root: info
    com.vs: DEBUG
    org.springframework.security: DEBUG

  # 文件输出
#  file:
    # windows 绝对路径
#    path: D:\Code\Github\Java-Repo\demo\_2024_10_18
    # windows 相对路径
#    path: log/

    # linux路径
    # path: /var/log/myapp
#    name: log/demo.log
  #    name: D:\Code\Github\Java-Repo\demo\_2024_10_18\demo.log

  # 指定日志输出格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"